[2025-06-19T13:02:18.427+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.register_model_task scheduled__2025-06-18T00:00:00+00:00 [queued]>
[2025-06-19T13:02:18.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.register_model_task scheduled__2025-06-18T00:00:00+00:00 [queued]>
[2025-06-19T13:02:18.433+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-06-19T13:02:18.463+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): register_model_task> on 2025-06-18 00:00:00+00:00
[2025-06-19T13:02:18.470+0000] {standard_task_runner.py:60} INFO - Started process 562 to run task
[2025-06-19T13:02:18.473+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'register_model_task', 'scheduled__2025-06-18T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp37_83hwn']
[2025-06-19T13:02:18.475+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask register_model_task
[2025-06-19T13:02:18.510+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T13:02:18.537+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.register_model_task scheduled__2025-06-18T00:00:00+00:00 [running]> on host b5d5b4f06c55
[2025-06-19T13:02:18.650+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='register_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-18T00:00:00+00:00'
[2025-06-19T13:02:18.651+0000] {logging_mixin.py:188} INFO - Starting model registration task...
[2025-06-19T13:02:18.668+0000] {logging_mixin.py:188} INFO - Artifact location: /opt/***/mlflow_artifacts
[2025-06-19T13:02:18.668+0000] {logging_mixin.py:188} INFO - Artifact location exists: True
[2025-06-19T13:02:18.669+0000] {logging_mixin.py:188} INFO - Artifact location permissions: 777
[2025-06-19T13:02:18.696+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T13:02:18.722+0000] {logging_mixin.py:188} INFO - No versions found for model 'lung_cancer_model'
[2025-06-19T13:02:18.722+0000] {logging_mixin.py:188} INFO - No model found in MLflow registry. Using the trained model.
[2025-06-19T13:02:18.799+0000] {logging_mixin.py:188} WARNING - 2025/06/19 13:02:18 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T13:02:18.819+0000] {logging_mixin.py:188} INFO - Started MLflow run: registration_run
[2025-06-19T13:02:18.819+0000] {logging_mixin.py:188} INFO - Run ID: 619d62fa84544777bfe23d59b9e49a62
[2025-06-19T13:02:18.836+0000] {logging_mixin.py:188} INFO - Run artifact URI: /mlflow/artifacts/1/619d62fa84544777bfe23d59b9e49a62/artifacts
[2025-06-19T13:02:18.884+0000] {logging_mixin.py:188} INFO - Model saved locally to: /opt/***/models/model_20250619_130218.joblib
[2025-06-19T13:02:20.614+0000] {logging_mixin.py:188} WARNING - 2025/06/19 13:02:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-19T13:02:20.630+0000] {logging_mixin.py:188} INFO - Failed to log model directly to MLflow: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T13:02:20.631+0000] {logging_mixin.py:188} INFO - Failed to log model as artifact: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T13:02:20.631+0000] {logging_mixin.py:188} INFO - MLflow is not available. Skipping end_run.
[2025-06-19T13:02:20.632+0000] {python.py:202} INFO - Done. Returned value was: Model registration completed
[2025-06-19T13:02:20.734+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=lung_cancer_ml_pipeline, task_id=register_model_task, execution_date=20250618T000000, start_date=20250619T130218, end_date=20250619T130220
[2025-06-19T13:02:20.824+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T13:02:20.841+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
