[2025-06-19T11:19:57.156+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.register_model_task manual__2025-06-19T11:19:31+00:00 [queued]>
[2025-06-19T11:19:57.162+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.register_model_task manual__2025-06-19T11:19:31+00:00 [queued]>
[2025-06-19T11:19:57.163+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-06-19T11:19:57.201+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): register_model_task> on 2025-06-19 11:19:31+00:00
[2025-06-19T11:19:57.210+0000] {standard_task_runner.py:60} INFO - Started process 926 to run task
[2025-06-19T11:19:57.213+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'register_model_task', 'manual__2025-06-19T11:19:31+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpj_kocihi']
[2025-06-19T11:19:57.216+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask register_model_task
[2025-06-19T11:19:57.246+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T11:19:57.272+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.register_model_task manual__2025-06-19T11:19:31+00:00 [running]> on host 0064cba90111
[2025-06-19T11:19:57.377+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='register_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T11:19:31+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T11:19:31+00:00'
[2025-06-19T11:19:57.378+0000] {logging_mixin.py:188} INFO - Starting model registration task...
[2025-06-19T11:19:57.392+0000] {logging_mixin.py:188} INFO - Artifact location: /opt/***/mlflow_artifacts
[2025-06-19T11:19:57.393+0000] {logging_mixin.py:188} INFO - Artifact location exists: True
[2025-06-19T11:19:57.393+0000] {logging_mixin.py:188} INFO - Artifact location permissions: 777
[2025-06-19T11:19:57.417+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T11:19:57.438+0000] {logging_mixin.py:188} INFO - No versions found for model 'lung_cancer_model'
[2025-06-19T11:19:57.438+0000] {logging_mixin.py:188} INFO - No model found in MLflow registry. Using the trained model.
[2025-06-19T11:19:57.519+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:19:57 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T11:19:57.543+0000] {logging_mixin.py:188} INFO - Started MLflow run: registration_run
[2025-06-19T11:19:57.544+0000] {logging_mixin.py:188} INFO - Run ID: c24d7b5cde6a4353acea85733d9f623e
[2025-06-19T11:19:57.555+0000] {logging_mixin.py:188} INFO - Run artifact URI: /mlflow/artifacts/1/c24d7b5cde6a4353acea85733d9f623e/artifacts
[2025-06-19T11:19:57.605+0000] {logging_mixin.py:188} INFO - Model saved locally to: /opt/***/models/model_20250619_111957.joblib
[2025-06-19T11:19:59.441+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:19:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-19T11:19:59.457+0000] {logging_mixin.py:188} INFO - Failed to log model directly to MLflow: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T11:19:59.458+0000] {logging_mixin.py:188} INFO - Failed to log model as artifact: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T11:19:59.458+0000] {logging_mixin.py:188} INFO - MLflow is not available. Skipping end_run.
[2025-06-19T11:19:59.459+0000] {python.py:202} INFO - Done. Returned value was: Model registration completed
[2025-06-19T11:19:59.511+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=lung_cancer_ml_pipeline, task_id=register_model_task, execution_date=20250619T111931, start_date=20250619T111957, end_date=20250619T111959
[2025-06-19T11:19:59.565+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:19:59.580+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
