[2025-06-19T13:02:09.195+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T13:01:52.374357+00:00 [queued]>
[2025-06-19T13:02:09.202+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T13:01:52.374357+00:00 [queued]>
[2025-06-19T13:02:09.203+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-06-19T13:02:09.230+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_model_task> on 2025-06-19 13:01:52.374357+00:00
[2025-06-19T13:02:09.237+0000] {standard_task_runner.py:60} INFO - Started process 405 to run task
[2025-06-19T13:02:09.240+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'train_model_task', 'manual__2025-06-19T13:01:52.374357+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp9y67urjj']
[2025-06-19T13:02:09.242+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask train_model_task
[2025-06-19T13:02:09.276+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T13:02:09.303+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T13:01:52.374357+00:00 [running]> on host b5d5b4f06c55
[2025-06-19T13:02:09.396+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T13:01:52.374357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T13:01:52.374357+00:00'
[2025-06-19T13:02:09.397+0000] {logging_mixin.py:188} INFO - Starting model training task...
[2025-06-19T13:02:09.425+0000] {logging_mixin.py:188} INFO - Retrieved DataFrame with shape (1000, 21) from key 'lung_cancer:model_features'
[2025-06-19T13:02:09.431+0000] {logging_mixin.py:188} INFO - Artifact location: /opt/***/mlflow_artifacts
[2025-06-19T13:02:09.431+0000] {logging_mixin.py:188} INFO - Artifact location exists: True
[2025-06-19T13:02:09.432+0000] {logging_mixin.py:188} INFO - Artifact location permissions: 777
[2025-06-19T13:02:09.461+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T13:02:09.513+0000] {logging_mixin.py:188} WARNING - 2025/06/19 13:02:09 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T13:02:09.536+0000] {logging_mixin.py:188} INFO - Started MLflow run: training_run
[2025-06-19T13:02:09.536+0000] {logging_mixin.py:188} INFO - Run ID: 9217f1eb756549c1bc2e1471fa8c4a67
[2025-06-19T13:02:09.552+0000] {logging_mixin.py:188} INFO - Run artifact URI: /mlflow/artifacts/1/9217f1eb756549c1bc2e1471fa8c4a67/artifacts
[2025-06-19T13:02:09.570+0000] {logging_mixin.py:188} INFO - Splitting data into training and testing sets...
[2025-06-19T13:02:09.579+0000] {logging_mixin.py:188} INFO - Training set: 800 samples
[2025-06-19T13:02:09.580+0000] {logging_mixin.py:188} INFO - Testing set: 200 samples
[2025-06-19T13:02:09.580+0000] {logging_mixin.py:188} INFO - Starting model training process...
[2025-06-19T13:02:09.585+0000] {logging_mixin.py:188} INFO - Target variable appears to be continuous. Using regression model instead of classifier.
[2025-06-19T13:02:09.585+0000] {logging_mixin.py:188} INFO - Training RandomForestRegressor model...
[2025-06-19T13:02:10.123+0000] {logging_mixin.py:188} INFO - Model saved to: /opt/***/models/randomforestregressor_model.joblib
[2025-06-19T13:02:10.124+0000] {logging_mixin.py:188} INFO - Model training completed
[2025-06-19T13:02:10.142+0000] {logging_mixin.py:188} INFO - Logged 3 parameters
[2025-06-19T13:02:10.173+0000] {logging_mixin.py:188} INFO - Model saved locally to: /opt/***/models/model_20250619_130210.joblib
[2025-06-19T13:02:12.037+0000] {logging_mixin.py:188} WARNING - 2025/06/19 13:02:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-19T13:02:12.057+0000] {logging_mixin.py:188} INFO - Failed to log model directly to MLflow: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T13:02:12.058+0000] {logging_mixin.py:188} INFO - Failed to log model as artifact: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T13:02:12.062+0000] {logging_mixin.py:188} INFO - Stored DataFrame with shape (200, 21) at key 'lung_cancer:model_features:test'
[2025-06-19T13:02:12.163+0000] {logging_mixin.py:188} INFO - MLflow is not available. Skipping end_run.
[2025-06-19T13:02:12.167+0000] {python.py:202} INFO - Done. Returned value was: Model training completed
[2025-06-19T13:02:12.205+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=lung_cancer_ml_pipeline, task_id=train_model_task, execution_date=20250619T130152, start_date=20250619T130209, end_date=20250619T130212
[2025-06-19T13:02:12.251+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T13:02:12.278+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
