[2025-06-19T10:31:07.142+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:25:48+00:00 [queued]>
[2025-06-19T10:31:07.152+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:25:48+00:00 [queued]>
[2025-06-19T10:31:07.152+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-06-19T10:31:07.197+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_model_task> on 2025-06-19 10:25:48+00:00
[2025-06-19T10:31:07.206+0000] {standard_task_runner.py:60} INFO - Started process 383 to run task
[2025-06-19T10:31:07.210+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'train_model_task', 'manual__2025-06-19T10:25:48+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpi3x82for']
[2025-06-19T10:31:07.212+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask train_model_task
[2025-06-19T10:31:07.249+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T10:31:07.282+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:25:48+00:00 [running]> on host 50ee7aa98663
[2025-06-19T10:31:07.402+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T10:25:48+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T10:25:48+00:00'
[2025-06-19T10:31:07.403+0000] {logging_mixin.py:188} INFO - Starting model training task...
[2025-06-19T10:31:07.434+0000] {logging_mixin.py:188} INFO - Retrieved DataFrame with shape (1000, 21) from key 'lung_cancer:model_features'
[2025-06-19T10:31:07.466+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T10:31:07.516+0000] {logging_mixin.py:188} WARNING - 2025/06/19 10:31:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T10:31:07.536+0000] {logging_mixin.py:188} INFO - Started MLflow run: training_run
[2025-06-19T10:31:07.551+0000] {logging_mixin.py:188} INFO - Splitting data into training and testing sets...
[2025-06-19T10:31:07.559+0000] {logging_mixin.py:188} INFO - Training set: 800 samples
[2025-06-19T10:31:07.560+0000] {logging_mixin.py:188} INFO - Testing set: 200 samples
[2025-06-19T10:31:07.560+0000] {logging_mixin.py:188} INFO - Starting model training process...
[2025-06-19T10:31:07.564+0000] {logging_mixin.py:188} INFO - Training RandomForestClassifier model...
[2025-06-19T10:31:07.567+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 195, in train_model_task
    model, training_meta = train_model(X_train, y_train)
  File "/opt/airflow/src/models/training.py", line 98, in train_model
    model.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 390, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 749, in _validate_y_class_weight
    check_classification_targets(y)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 216, in check_classification_targets
    raise ValueError(
ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
[2025-06-19T10:31:07.576+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=lung_cancer_ml_pipeline, task_id=train_model_task, execution_date=20250619T102548, start_date=20250619T103107, end_date=20250619T103107
[2025-06-19T10:31:07.608+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task train_model_task (Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.; 383)
[2025-06-19T10:31:07.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-19T10:31:07.655+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
