[2025-06-19T10:40:54.094+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:35:33+00:00 [queued]>
[2025-06-19T10:40:54.100+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:35:33+00:00 [queued]>
[2025-06-19T10:40:54.101+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-06-19T10:40:54.133+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_model_task> on 2025-06-19 10:35:33+00:00
[2025-06-19T10:40:54.140+0000] {standard_task_runner.py:60} INFO - Started process 798 to run task
[2025-06-19T10:40:54.143+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'train_model_task', 'manual__2025-06-19T10:35:33+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp06qmlw07']
[2025-06-19T10:40:54.145+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask train_model_task
[2025-06-19T10:40:54.176+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T10:40:54.203+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T10:35:33+00:00 [running]> on host 50ee7aa98663
[2025-06-19T10:40:54.309+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T10:35:33+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T10:35:33+00:00'
[2025-06-19T10:40:54.310+0000] {logging_mixin.py:188} INFO - Starting model training task...
[2025-06-19T10:40:54.336+0000] {logging_mixin.py:188} INFO - Retrieved DataFrame with shape (1000, 21) from key 'lung_cancer:model_features'
[2025-06-19T10:40:54.341+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 186, in train_model_task
    mlflow_tracker = MLFlowTracker()
  File "/opt/airflow/src/utils/mlflow_utils.py", line 30, in __init__
    mlflow.tracking.utils._TRACKING_URI_ENV_VAR = "MLFLOW_TRACKING_URI"
AttributeError: module 'mlflow.tracking' has no attribute 'utils'
[2025-06-19T10:40:54.348+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=lung_cancer_ml_pipeline, task_id=train_model_task, execution_date=20250619T103533, start_date=20250619T104054, end_date=20250619T104054
[2025-06-19T10:40:54.407+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task train_model_task (module 'mlflow.tracking' has no attribute 'utils'; 798)
[2025-06-19T10:40:54.445+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-19T10:40:54.463+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
