[2025-06-19T11:21:00.849+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T11:15:39.535668+00:00 [queued]>
[2025-06-19T11:21:00.856+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T11:15:39.535668+00:00 [queued]>
[2025-06-19T11:21:00.857+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-06-19T11:21:00.892+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_model_task> on 2025-06-19 11:15:39.535668+00:00
[2025-06-19T11:21:00.899+0000] {standard_task_runner.py:60} INFO - Started process 973 to run task
[2025-06-19T11:21:00.902+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'lung_cancer_ml_pipeline', 'train_model_task', 'manual__2025-06-19T11:15:39.535668+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpay6xw8j_']
[2025-06-19T11:21:00.905+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask train_model_task
[2025-06-19T11:21:00.942+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-19T11:21:00.966+0000] {task_command.py:423} INFO - Running <TaskInstance: lung_cancer_ml_pipeline.train_model_task manual__2025-06-19T11:15:39.535668+00:00 [running]> on host 0064cba90111
[2025-06-19T11:21:01.067+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lung_cancer_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T11:15:39.535668+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T11:15:39.535668+00:00'
[2025-06-19T11:21:01.070+0000] {logging_mixin.py:188} INFO - Starting model training task...
[2025-06-19T11:21:01.098+0000] {logging_mixin.py:188} INFO - Retrieved DataFrame with shape (1000, 21) from key 'lung_cancer:model_features'
[2025-06-19T11:21:01.103+0000] {logging_mixin.py:188} INFO - Artifact location: /opt/***/mlflow_artifacts
[2025-06-19T11:21:01.104+0000] {logging_mixin.py:188} INFO - Artifact location exists: True
[2025-06-19T11:21:01.104+0000] {logging_mixin.py:188} INFO - Artifact location permissions: 777
[2025-06-19T11:21:01.127+0000] {logging_mixin.py:188} INFO - Using existing experiment 'lung_cancer_mortality_prediction' with ID: 1
[2025-06-19T11:21:01.192+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:21:01 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-19T11:21:01.224+0000] {logging_mixin.py:188} INFO - Started MLflow run: training_run
[2025-06-19T11:21:01.225+0000] {logging_mixin.py:188} INFO - Run ID: 81dea81359bc4228b0fb6190d03fae90
[2025-06-19T11:21:01.241+0000] {logging_mixin.py:188} INFO - Run artifact URI: /mlflow/artifacts/1/81dea81359bc4228b0fb6190d03fae90/artifacts
[2025-06-19T11:21:01.255+0000] {logging_mixin.py:188} INFO - Splitting data into training and testing sets...
[2025-06-19T11:21:01.263+0000] {logging_mixin.py:188} INFO - Training set: 800 samples
[2025-06-19T11:21:01.264+0000] {logging_mixin.py:188} INFO - Testing set: 200 samples
[2025-06-19T11:21:01.264+0000] {logging_mixin.py:188} INFO - Starting model training process...
[2025-06-19T11:21:01.268+0000] {logging_mixin.py:188} INFO - Target variable appears to be continuous. Using regression model instead of classifier.
[2025-06-19T11:21:01.269+0000] {logging_mixin.py:188} INFO - Training RandomForestRegressor model...
[2025-06-19T11:21:01.798+0000] {logging_mixin.py:188} INFO - Model saved to: /opt/***/models/randomforestregressor_model.joblib
[2025-06-19T11:21:01.799+0000] {logging_mixin.py:188} INFO - Model training completed
[2025-06-19T11:21:01.816+0000] {logging_mixin.py:188} INFO - Logged 3 parameters
[2025-06-19T11:21:01.849+0000] {logging_mixin.py:188} INFO - Model saved locally to: /opt/***/models/model_20250619_112101.joblib
[2025-06-19T11:21:03.753+0000] {logging_mixin.py:188} WARNING - 2025/06/19 11:21:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-19T11:21:03.771+0000] {logging_mixin.py:188} INFO - Failed to log model directly to MLflow: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T11:21:03.772+0000] {logging_mixin.py:188} INFO - Failed to log model as artifact: [Errno 13] Permission denied: '/mlflow'
[2025-06-19T11:21:03.776+0000] {logging_mixin.py:188} INFO - Stored DataFrame with shape (200, 21) at key 'lung_cancer:model_features:test'
[2025-06-19T11:21:03.869+0000] {logging_mixin.py:188} INFO - MLflow is not available. Skipping end_run.
[2025-06-19T11:21:03.871+0000] {python.py:202} INFO - Done. Returned value was: Model training completed
[2025-06-19T11:21:03.917+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=lung_cancer_ml_pipeline, task_id=train_model_task, execution_date=20250619T111539, start_date=20250619T112100, end_date=20250619T112103
[2025-06-19T11:21:04.033+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:21:04.058+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
